logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Messenger]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"
apkmirror-arch = "arm64-v8a"
build-mode = "module"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
apkmirror-arch = "arm64-v8a"
build-mode = "module"
included-patches = "'MaterialYou'"
excluded-patches = "'Hide video action buttons' 'Navigation buttons' 'Hide autoplay button' 'Hide player buttons' 'Hide cast button' 'Enable debugging' 'GmsCore support'"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "arm64-v8a"
build-mode = "module"
included-patches = "'Permanent repeat' 'Amoled'"
excluded-patches = "'GmsCore support' 'Bypass certificate checks'"

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
apkmirror-arch = "arm64-v8a"
build-mode = "module"

[Facebook]
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"
apkmirror-arch = "arm64-v8a"
build-mode = "module"

